[project]
name = "recon"
version = "1.0.0"
description = "A web application that simplifies economic data."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"